export const ActionTypes = {
    PRODUCT_LIST: "PRODUCT_LIST",
    SIGNUP_DATA: "SIGNUP_DATA",
    LOGIN_DATA: "LOGIN_DATA",
    REMOVE_LOGIN_DATA: "REMOVE_LOGIN_DATA",
    INC_DATA: "INC_DATA",
    DEC_DATA: "DEC_DATA",
    ADD_TO_CARD: "ADD_TO_CARD",
    REMOVE_TO_CARD: "REMOVE_TO_CARD",
    REMOVE_All_DATA: "REMOVE_All_DATA",

    ADD_TO_CARD_ARR_ID: "ADD_TO_CARD_ARR_ID",
    REMOVE_TO_CARD_ARR_ID: "REMOVE_TO_CARD_ARR_ID",
    REMOVE_All_ARR_ID: "REMOVE_All_ARR_ID",

    STATE_DATA: "STATE_DATA",
    CITY_DATA: "CITY_DATA",
    REMOVE_STATE_DATA: "REMOVE_STATE_DATA",
    REMOVE_CITY_DATA: "REMOVE_CITY_DATA"
}